### ISSUE TITLE
experimental syntax **'decorators-legacy'** isn't currently enabled meteor

### ISSUE THREAD

**Issue by pawansingh00** [maxnowack/meteor-sync-eventemitter#8]
I am getting this Error when using this package with Meteor 1.7

Support for the    experimental syntax **'decorators-legacy'** isn't currently enabled meteor
@maxnowack can you please suggest

**Comment by maxnowack** [comment]
If you want to use the decorator syntax, you have to install `@babel/plugin-proposal-decorators`.
Alternatively you can use the function without the decorator syntax:
````js
  import { Meteor } from 'meteor/meteor';
  import sync from 'meteor-sync-eventemitter';

  const SyncedStream = sync({ collectionName: 'stream', emitFn: '_emit' })(class SyncedStream extends Meteor.Streamer {
    constructor() {
      super('streamname');
      this.allowRead( … );
      this.allowWrite( … );
    }
  })

  const stream = new SyncedStream()
  stream.emit( … );
  stream.on( … );
````

**Comment by pawansingh00** [comment]
When I am doing like this it says SyncedStream is not defined

@maxnowack

**Comment by maxnowack** [comment]
Try this:
````js
  const SyncedStream = sync({ collectionName: 'stream', emitFn: '_emit' })(class SyncedStream extends Meteor.Streamer {
    constructor() {
      super('streamname');
      this.allowRead( … );
      this.allowWrite( … );
    }
  })
````
I've also updated my code example above

**Comment by pawansingh00** [comment]
Yeah, Actually just now I figured it out.
Thanks Anyways.

**Comment by bikramchoudhury** [comment]
I have integrated successfully with `meteor-sync-eventemitter`, and this is working without cluster config **but not working with cluster config  CLUSTER_WORKERS_COUNT**. This is my bellow code.

```
import { Meteor } from 'meteor/meteor';
import sync from 'meteor-sync-eventemitter';

const _syncedStreams = sync({ collectionName: 'stream', emitFn: '_emit' })
(class SyncedStream extends Meteor.Streamer {
    constructor() {
        super('streamname');
    }
});

const TestStreams = new _syncedStreams();


TestStreams.allowRead('all');
TestStreams.allowWrite('all');
```
```
// Emiting Event
TestStreams.emit(Meteor.userId(),{
    data: {
        client: client
    },
    from: 'Server'
});
```
```
// subscription event 

TestStreams.on(Meteor.userId(), function (dataObject) {
   console.log("TestStreams dataObject: ", dataObject);
});
```
@maxnowack - Please help.

**Comment by pawansingh00** [comment]
Does this package Depends on Meteor Pub-Sub concept?
@maxnowack

**Comment by maxnowack** [comment]
@pawansingh-snapwiz no, it just depends on the meteor mongo package
@bikramchoudhury I don't have any experience with cluster, so I don't have a clue why it isn't working
